Allow script to work as local or global install

diff --git a/bin/html-wiki b/bin/html-wiki
--- a/bin/html-wiki
+++ b/bin/html-wiki
@@ -1,2 +1,13 @@
 #!/usr/bin/env bash
-node ./server/cli.mts "$@"
+DIR=@reedspool/html-wiki
+CLI=server/cli.mts
+if [ -f "$(npm root)/$DIR" ]; then
+	node "$(npm root)/$DIR/$CLI" "$@"
+elif [ -f "$(npm root -g)/$DIR" ]; then
+	node "$(npm root -g)/$DIR/$CLI" "$@"
+else
+	echo "Checked npm root: '$(npm root)'"
+	echo "Checked npm root -g: '$(npm root -g)'"
+	echo "Error: Unable to find '$DIR' executable's node_modules directory"
+	exit 1
+fi
